const CONJUNTO_CARACTERES_ESPECIAIS = Array.from('@!#*%$');
const CONJUNTO_NUMEROS = Array.from('0123456789');
const CONJUNTO_ALFABETO_MINUSCULO = Array.from('abcçdefghijklmnopqrstuvwxyz');
const CONJUNTO_ALFABETO_MAIUSCULO = CONJUNTO_ALFABETO_MINUSCULO.map(vl => vl.toUpperCase());

export { CONJUNTO_CARACTERES_ESPECIAIS, 
  CONJUNTO_NUMEROS, 
  CONJUNTO_ALFABETO_MINUSCULO, 
  CONJUNTO_ALFABETO_MAIUSCULO 
}